import { Audit,validateAudit } from './evidence';
export type Saved={id:string;created:number;salt:number[];iv:number[];ciphertext:ArrayBuffer};
async function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('rsat-encrypted-history',1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Local history unavailable.'));});}
async function transaction<T>(mode:IDBTransactionMode,action:(store:IDBObjectStore)=>IDBRequest<T>){const database=await db();try{return await new Promise<T>((resolve,reject)=>{const tx=database.transaction('snapshots',mode);const request=action(tx.objectStore('snapshots'));let result:T;request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(Error('Local history transaction failed.'));tx.onerror=()=>reject(Error('Local history write failed.'));});}finally{database.close();}}
async function key(password:string,salt:Uint8Array){if(password.length<12)throw Error('Use a passphrase of at least 12 characters.');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt as BufferSource,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function listHistory(){const rows=await transaction<Saved[]>('readonly',s=>s.getAll());return rows.sort((a,b)=>b.created-a.created);}
export async function saveHistory(audit:Audit,password:string,keep:number){if(!Number.isInteger(keep)||keep<1||keep>100)throw Error('Retention must be 1–100 snapshots.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const id=crypto.randomUUID();const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},await key(password,salt),new TextEncoder().encode(JSON.stringify(audit)));await transaction('readwrite',s=>s.put({id,created:Date.now(),salt:[...salt],iv:[...iv],ciphertext}));const rows=await listHistory();for(const row of rows.slice(keep))await transaction('readwrite',s=>s.delete(row.id));return listHistory();}
export async function loadHistory(row:Saved,password:string){try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(row.iv),additionalData:new TextEncoder().encode(row.id)},await key(password,new Uint8Array(row.salt)),row.ciphertext);return validateAudit(JSON.parse(new TextDecoder().decode(plain)));}catch{throw Error('Unable to unlock this snapshot. Check the passphrase.');}}
export async function clearHistory(){await transaction('readwrite',s=>s.clear());}
